[2024-09-13T16:25:48.760+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.load_task manual__2024-09-13T16:25:45.268248+00:00 [queued]>
[2024-09-13T16:25:48.767+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.load_task manual__2024-09-13T16:25:45.268248+00:00 [queued]>
[2024-09-13T16:25:48.767+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T16:25:48.769+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-13T16:25:48.769+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T16:25:48.872+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_task> on 2024-09-13 16:25:45.268248+00:00
[2024-09-13T16:25:48.875+0000] {standard_task_runner.py:55} INFO - Started process 847 to run task
[2024-09-13T16:25:48.877+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag', 'load_task', 'manual__2024-09-13T16:25:45.268248+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpl7syi1gb']
[2024-09-13T16:25:48.879+0000] {standard_task_runner.py:83} INFO - Job 61: Subtask load_task
[2024-09-13T16:25:48.892+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-13T16:25:48.931+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_pipeline_dag.load_task manual__2024-09-13T16:25:45.268248+00:00 [running]> on host 2656b950921d
[2024-09-13T16:25:49.074+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_pipeline_dag
AIRFLOW_CTX_TASK_ID=load_task
AIRFLOW_CTX_EXECUTION_DATE=2024-09-13T16:25:45.268248+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-13T16:25:45.268248+00:00
[2024-09-13T16:25:49.079+0000] {logging_mixin.py:137} INFO - Failed to load data into PostgreSQL: 'str' object has no attribute 'get'
[2024-09-13T16:25:49.079+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/tasks/loader.py", line 24, in loader
    row.get('Province_State', 'N/A'),
AttributeError: 'str' object has no attribute 'get'
[2024-09-13T16:25:49.087+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_pipeline_dag, task_id=load_task, execution_date=20240913T162545, start_date=20240913T162548, end_date=20240913T162549
[2024-09-13T16:25:49.097+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 61 for task load_task ('str' object has no attribute 'get'; 847)
[2024-09-13T16:25:49.131+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-13T16:25:49.144+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
