[2024-09-13T16:01:50.505+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.extract_task manual__2024-09-13T16:01:49.947272+00:00 [queued]>
[2024-09-13T16:01:50.512+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.extract_task manual__2024-09-13T16:01:49.947272+00:00 [queued]>
[2024-09-13T16:01:50.512+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T16:01:50.512+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-13T16:01:50.512+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-13T16:01:50.607+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_task> on 2024-09-13 16:01:49.947272+00:00
[2024-09-13T16:01:50.611+0000] {standard_task_runner.py:55} INFO - Started process 217 to run task
[2024-09-13T16:01:50.614+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag', 'extract_task', 'manual__2024-09-13T16:01:49.947272+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpkaf2evsf']
[2024-09-13T16:01:50.615+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask extract_task
[2024-09-13T16:01:50.628+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-13T16:01:50.666+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_pipeline_dag.extract_task manual__2024-09-13T16:01:49.947272+00:00 [running]> on host 2656b950921d
[2024-09-13T16:01:50.730+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_pipeline_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2024-09-13T16:01:49.947272+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-13T16:01:49.947272+00:00
[2024-09-13T16:01:50.771+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052 InsecureRequestWarning: Unverified HTTPS request is being made to host 'raw.githubusercontent.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
[2024-09-13T16:01:51.025+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/tasks/extractor.py", line 18, in extractor
    data = pd.read_csv(StringIO(response.text))  # Read CSV data into a pandas DataFrame
NameError: name 'StringIO' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/tasks/extractor.py", line 23, in extractor
    print(f"Failed to extract data from {url}: {e}")
NameError: name 'url' is not defined
[2024-09-13T16:01:51.035+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_pipeline_dag, task_id=extract_task, execution_date=20240913T160149, start_date=20240913T160150, end_date=20240913T160151
[2024-09-13T16:01:51.048+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task extract_task (name 'url' is not defined; 217)
[2024-09-13T16:01:51.069+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-13T16:01:51.092+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
