[2024-09-12T02:49:20.281+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.extract_task manual__2024-09-12T02:49:19.451254+00:00 [queued]>
[2024-09-12T02:49:20.291+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: etl_pipeline_dag.extract_task manual__2024-09-12T02:49:19.451254+00:00 [queued]>
[2024-09-12T02:49:20.292+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-12T02:49:20.292+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2024-09-12T02:49:20.292+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-12T02:49:20.307+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_task> on 2024-09-12 02:49:19.451254+00:00
[2024-09-12T02:49:20.311+0000] {standard_task_runner.py:55} INFO - Started process 221 to run task
[2024-09-12T02:49:20.316+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline_dag', 'extract_task', 'manual__2024-09-12T02:49:19.451254+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpiycnbar4']
[2024-09-12T02:49:20.454+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask extract_task
[2024-09-12T02:49:20.468+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-12T02:49:20.545+0000] {task_command.py:389} INFO - Running <TaskInstance: etl_pipeline_dag.extract_task manual__2024-09-12T02:49:19.451254+00:00 [running]> on host 94e336337df0
[2024-09-12T02:49:20.589+0000] {abstractoperator.py:596} ERROR - Exception rendering Jinja template for task 'extract_task', field 'op_kwargs'. Template: {'url': '{{ var.value.covid_data_url }}'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 646, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py", line 103, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable covid_data_url does not exist'
[2024-09-12T02:49:20.591+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1497, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2119, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1196, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 646, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py", line 103, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable covid_data_url does not exist'
[2024-09-12T02:49:20.598+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=etl_pipeline_dag, task_id=extract_task, execution_date=20240912T024919, start_date=20240912T024920, end_date=20240912T024920
[2024-09-12T02:49:20.607+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task extract_task ('Variable covid_data_url does not exist'; 221)
[2024-09-12T02:49:20.649+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-12T02:49:20.769+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
